/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as ColumnDefinitionsRouteImport } from './routes/column-definitions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as EntitiesIndexRouteImport } from './routes/entities.index'
import { Route as ConnectorsIndexRouteImport } from './routes/connectors.index'
import { Route as ColumnDefinitionsIndexRouteImport } from './routes/column-definitions.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as EntitiesEntityIdRouteImport } from './routes/entities.$entityId'
import { Route as ConnectorsConnectorInstanceIdRouteImport } from './routes/connectors.$connectorInstanceId'
import { Route as ColumnDefinitionsColumnDefinitionIdRouteImport } from './routes/column-definitions.$columnDefinitionId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ColumnDefinitionsRoute = ColumnDefinitionsRouteImport.update({
  id: '/column-definitions',
  path: '/column-definitions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const EntitiesIndexRoute = EntitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntitiesRoute,
} as any)
const ConnectorsIndexRoute = ConnectorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnectorsRoute,
} as any)
const ColumnDefinitionsIndexRoute = ColumnDefinitionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ColumnDefinitionsRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const EntitiesEntityIdRoute = EntitiesEntityIdRouteImport.update({
  id: '/$entityId',
  path: '/$entityId',
  getParentRoute: () => EntitiesRoute,
} as any)
const ConnectorsConnectorInstanceIdRoute =
  ConnectorsConnectorInstanceIdRouteImport.update({
    id: '/$connectorInstanceId',
    path: '/$connectorInstanceId',
    getParentRoute: () => ConnectorsRoute,
  } as any)
const ColumnDefinitionsColumnDefinitionIdRoute =
  ColumnDefinitionsColumnDefinitionIdRouteImport.update({
    id: '/$columnDefinitionId',
    path: '/$columnDefinitionId',
    getParentRoute: () => ColumnDefinitionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/column-definitions': typeof ColumnDefinitionsRouteWithChildren
  '/connectors': typeof ConnectorsRouteWithChildren
  '/entities': typeof EntitiesRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/column-definitions/$columnDefinitionId': typeof ColumnDefinitionsColumnDefinitionIdRoute
  '/connectors/$connectorInstanceId': typeof ConnectorsConnectorInstanceIdRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/column-definitions/': typeof ColumnDefinitionsIndexRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/entities/': typeof EntitiesIndexRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/column-definitions/$columnDefinitionId': typeof ColumnDefinitionsColumnDefinitionIdRoute
  '/connectors/$connectorInstanceId': typeof ConnectorsConnectorInstanceIdRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/column-definitions': typeof ColumnDefinitionsIndexRoute
  '/connectors': typeof ConnectorsIndexRoute
  '/entities': typeof EntitiesIndexRoute
  '/jobs': typeof JobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/column-definitions': typeof ColumnDefinitionsRouteWithChildren
  '/connectors': typeof ConnectorsRouteWithChildren
  '/entities': typeof EntitiesRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/column-definitions/$columnDefinitionId': typeof ColumnDefinitionsColumnDefinitionIdRoute
  '/connectors/$connectorInstanceId': typeof ConnectorsConnectorInstanceIdRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/column-definitions/': typeof ColumnDefinitionsIndexRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/entities/': typeof EntitiesIndexRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/column-definitions'
    | '/connectors'
    | '/entities'
    | '/jobs'
    | '/login'
    | '/settings'
    | '/column-definitions/$columnDefinitionId'
    | '/connectors/$connectorInstanceId'
    | '/entities/$entityId'
    | '/jobs/$jobId'
    | '/column-definitions/'
    | '/connectors/'
    | '/entities/'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/column-definitions/$columnDefinitionId'
    | '/connectors/$connectorInstanceId'
    | '/entities/$entityId'
    | '/jobs/$jobId'
    | '/column-definitions'
    | '/connectors'
    | '/entities'
    | '/jobs'
  id:
    | '__root__'
    | '/'
    | '/column-definitions'
    | '/connectors'
    | '/entities'
    | '/jobs'
    | '/login'
    | '/settings'
    | '/column-definitions/$columnDefinitionId'
    | '/connectors/$connectorInstanceId'
    | '/entities/$entityId'
    | '/jobs/$jobId'
    | '/column-definitions/'
    | '/connectors/'
    | '/entities/'
    | '/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColumnDefinitionsRoute: typeof ColumnDefinitionsRouteWithChildren
  ConnectorsRoute: typeof ConnectorsRouteWithChildren
  EntitiesRoute: typeof EntitiesRouteWithChildren
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/column-definitions': {
      id: '/column-definitions'
      path: '/column-definitions'
      fullPath: '/column-definitions'
      preLoaderRoute: typeof ColumnDefinitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/entities/': {
      id: '/entities/'
      path: '/'
      fullPath: '/entities/'
      preLoaderRoute: typeof EntitiesIndexRouteImport
      parentRoute: typeof EntitiesRoute
    }
    '/connectors/': {
      id: '/connectors/'
      path: '/'
      fullPath: '/connectors/'
      preLoaderRoute: typeof ConnectorsIndexRouteImport
      parentRoute: typeof ConnectorsRoute
    }
    '/column-definitions/': {
      id: '/column-definitions/'
      path: '/'
      fullPath: '/column-definitions/'
      preLoaderRoute: typeof ColumnDefinitionsIndexRouteImport
      parentRoute: typeof ColumnDefinitionsRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/entities/$entityId': {
      id: '/entities/$entityId'
      path: '/$entityId'
      fullPath: '/entities/$entityId'
      preLoaderRoute: typeof EntitiesEntityIdRouteImport
      parentRoute: typeof EntitiesRoute
    }
    '/connectors/$connectorInstanceId': {
      id: '/connectors/$connectorInstanceId'
      path: '/$connectorInstanceId'
      fullPath: '/connectors/$connectorInstanceId'
      preLoaderRoute: typeof ConnectorsConnectorInstanceIdRouteImport
      parentRoute: typeof ConnectorsRoute
    }
    '/column-definitions/$columnDefinitionId': {
      id: '/column-definitions/$columnDefinitionId'
      path: '/$columnDefinitionId'
      fullPath: '/column-definitions/$columnDefinitionId'
      preLoaderRoute: typeof ColumnDefinitionsColumnDefinitionIdRouteImport
      parentRoute: typeof ColumnDefinitionsRoute
    }
  }
}

interface ColumnDefinitionsRouteChildren {
  ColumnDefinitionsColumnDefinitionIdRoute: typeof ColumnDefinitionsColumnDefinitionIdRoute
  ColumnDefinitionsIndexRoute: typeof ColumnDefinitionsIndexRoute
}

const ColumnDefinitionsRouteChildren: ColumnDefinitionsRouteChildren = {
  ColumnDefinitionsColumnDefinitionIdRoute:
    ColumnDefinitionsColumnDefinitionIdRoute,
  ColumnDefinitionsIndexRoute: ColumnDefinitionsIndexRoute,
}

const ColumnDefinitionsRouteWithChildren =
  ColumnDefinitionsRoute._addFileChildren(ColumnDefinitionsRouteChildren)

interface ConnectorsRouteChildren {
  ConnectorsConnectorInstanceIdRoute: typeof ConnectorsConnectorInstanceIdRoute
  ConnectorsIndexRoute: typeof ConnectorsIndexRoute
}

const ConnectorsRouteChildren: ConnectorsRouteChildren = {
  ConnectorsConnectorInstanceIdRoute: ConnectorsConnectorInstanceIdRoute,
  ConnectorsIndexRoute: ConnectorsIndexRoute,
}

const ConnectorsRouteWithChildren = ConnectorsRoute._addFileChildren(
  ConnectorsRouteChildren,
)

interface EntitiesRouteChildren {
  EntitiesEntityIdRoute: typeof EntitiesEntityIdRoute
  EntitiesIndexRoute: typeof EntitiesIndexRoute
}

const EntitiesRouteChildren: EntitiesRouteChildren = {
  EntitiesEntityIdRoute: EntitiesEntityIdRoute,
  EntitiesIndexRoute: EntitiesIndexRoute,
}

const EntitiesRouteWithChildren = EntitiesRoute._addFileChildren(
  EntitiesRouteChildren,
)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColumnDefinitionsRoute: ColumnDefinitionsRouteWithChildren,
  ConnectorsRoute: ConnectorsRouteWithChildren,
  EntitiesRoute: EntitiesRouteWithChildren,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
