/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as ConnectorsIndexRouteImport } from './routes/connectors.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as ConnectorsConnectorInstanceIdRouteImport } from './routes/connectors.$connectorInstanceId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const ConnectorsIndexRoute = ConnectorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnectorsRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const ConnectorsConnectorInstanceIdRoute =
  ConnectorsConnectorInstanceIdRouteImport.update({
    id: '/$connectorInstanceId',
    path: '/$connectorInstanceId',
    getParentRoute: () => ConnectorsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/connectors/$connectorInstanceId': typeof ConnectorsConnectorInstanceIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/connectors/$connectorInstanceId': typeof ConnectorsConnectorInstanceIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/connectors': typeof ConnectorsIndexRoute
  '/jobs': typeof JobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/connectors/$connectorInstanceId': typeof ConnectorsConnectorInstanceIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connectors'
    | '/jobs'
    | '/login'
    | '/settings'
    | '/connectors/$connectorInstanceId'
    | '/jobs/$jobId'
    | '/connectors/'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/connectors/$connectorInstanceId'
    | '/jobs/$jobId'
    | '/connectors'
    | '/jobs'
  id:
    | '__root__'
    | '/'
    | '/connectors'
    | '/jobs'
    | '/login'
    | '/settings'
    | '/connectors/$connectorInstanceId'
    | '/jobs/$jobId'
    | '/connectors/'
    | '/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectorsRoute: typeof ConnectorsRouteWithChildren
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/connectors/': {
      id: '/connectors/'
      path: '/'
      fullPath: '/connectors/'
      preLoaderRoute: typeof ConnectorsIndexRouteImport
      parentRoute: typeof ConnectorsRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/connectors/$connectorInstanceId': {
      id: '/connectors/$connectorInstanceId'
      path: '/$connectorInstanceId'
      fullPath: '/connectors/$connectorInstanceId'
      preLoaderRoute: typeof ConnectorsConnectorInstanceIdRouteImport
      parentRoute: typeof ConnectorsRoute
    }
  }
}

interface ConnectorsRouteChildren {
  ConnectorsConnectorInstanceIdRoute: typeof ConnectorsConnectorInstanceIdRoute
  ConnectorsIndexRoute: typeof ConnectorsIndexRoute
}

const ConnectorsRouteChildren: ConnectorsRouteChildren = {
  ConnectorsConnectorInstanceIdRoute: ConnectorsConnectorInstanceIdRoute,
  ConnectorsIndexRoute: ConnectorsIndexRoute,
}

const ConnectorsRouteWithChildren = ConnectorsRoute._addFileChildren(
  ConnectorsRouteChildren,
)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectorsRoute: ConnectorsRouteWithChildren,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
