export enum ApiCode {
  // Profile
  PROFILE_MISSING_TOKEN = "PROFILE_MISSING_TOKEN",
  PROFILE_FETCH_FAILED = "PROFILE_FETCH_FAILED",
  PROFILE_INVALID_RESPONSE = "PROFILE_INVALID_RESPONSE",
  PROFILE_USER_NOT_FOUND = "PROFILE_USER_NOT_FOUND",

  // Auth
  AUTH_UPSTREAM_ERROR = "AUTH_UPSTREAM_ERROR",

  // Health
  HEALTH_CHECK_FAILED = "HEALTH_CHECK_FAILED",

  // Organization
  ORGANIZATION_USER_NOT_FOUND = "ORGANIZATION_USER_NOT_FOUND",
  ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND",
  ORGANIZATION_FETCH_FAILED = "ORGANIZATION_FETCH_FAILED",

  // Webhooks
  WEBHOOK_MISSING_SIGNATURE = "WEBHOOK_MISSING_SIGNATURE",
  WEBHOOK_INVALID_SIGNATURE = "WEBHOOK_INVALID_SIGNATURE",
  WEBHOOK_INVALID_PAYLOAD = "WEBHOOK_INVALID_PAYLOAD",
  WEBHOOK_SYNC_FAILED = "WEBHOOK_SYNC_FAILED",
  WEBHOOK_MISSING_SECRET = "WEBHOOK_MISSING_SECRET",

  // Connector Definitions
  CONNECTOR_DEFINITION_NOT_FOUND = "CONNECTOR_DEFINITION_NOT_FOUND",
  CONNECTOR_DEFINITION_FETCH_FAILED = "CONNECTOR_DEFINITION_FETCH_FAILED",

  // Connector Instances
  CONNECTOR_INSTANCE_NOT_FOUND = "CONNECTOR_INSTANCE_NOT_FOUND",
  CONNECTOR_INSTANCE_FETCH_FAILED = "CONNECTOR_INSTANCE_FETCH_FAILED",
  CONNECTOR_INSTANCE_INVALID_PAYLOAD = "CONNECTOR_INSTANCE_INVALID_PAYLOAD",
  CONNECTOR_INSTANCE_CREATE_FAILED = "CONNECTOR_INSTANCE_CREATE_FAILED",
  CONNECTOR_INSTANCE_USER_NOT_FOUND = "CONNECTOR_INSTANCE_USER_NOT_FOUND",

  // Session
  SESSION_PROMPT_INVALID = "SESSION_PROMPT_INVALID",
  SESSION_STREAM_FAILED = "SESSION_STREAM_FAILED",
  SESSION_USER_NOT_FOUND = "SESSION_USER_NOT_FOUND",

  // Jobs
  JOB_NOT_FOUND = "JOB_NOT_FOUND",
  JOB_ALREADY_TERMINAL = "JOB_ALREADY_TERMINAL",
  JOB_ENQUEUE_FAILED = "JOB_ENQUEUE_FAILED",
  JOB_UNAUTHORIZED = "JOB_UNAUTHORIZED",
  JOB_INVALID_PAYLOAD = "JOB_INVALID_PAYLOAD",
  JOB_FETCH_FAILED = "JOB_FETCH_FAILED",
  JOB_CANCEL_FAILED = "JOB_CANCEL_FAILED",
  JOB_USER_NOT_FOUND = "JOB_USER_NOT_FOUND",
}
