export enum ApiCode {
  // Profile
  PROFILE_MISSING_TOKEN = "PROFILE_MISSING_TOKEN",
  PROFILE_FETCH_FAILED = "PROFILE_FETCH_FAILED",
  PROFILE_INVALID_RESPONSE = "PROFILE_INVALID_RESPONSE",
  PROFILE_USER_NOT_FOUND = "PROFILE_USER_NOT_FOUND",

  // Auth
  AUTH_UPSTREAM_ERROR = "AUTH_UPSTREAM_ERROR",

  // Health
  HEALTH_CHECK_FAILED = "HEALTH_CHECK_FAILED",

  // Organization
  ORGANIZATION_USER_NOT_FOUND = "ORGANIZATION_USER_NOT_FOUND",
  ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND",
  ORGANIZATION_FETCH_FAILED = "ORGANIZATION_FETCH_FAILED",

  // Webhooks
  WEBHOOK_MISSING_SIGNATURE = "WEBHOOK_MISSING_SIGNATURE",
  WEBHOOK_INVALID_SIGNATURE = "WEBHOOK_INVALID_SIGNATURE",
  WEBHOOK_INVALID_PAYLOAD = "WEBHOOK_INVALID_PAYLOAD",
  WEBHOOK_SYNC_FAILED = "WEBHOOK_SYNC_FAILED",
  WEBHOOK_MISSING_SECRET = "WEBHOOK_MISSING_SECRET",

  // Connector Definitions
  CONNECTOR_DEFINITION_NOT_FOUND = "CONNECTOR_DEFINITION_NOT_FOUND",
  CONNECTOR_DEFINITION_FETCH_FAILED = "CONNECTOR_DEFINITION_FETCH_FAILED",

  // Connector Instances
  CONNECTOR_INSTANCE_NOT_FOUND = "CONNECTOR_INSTANCE_NOT_FOUND",
  CONNECTOR_INSTANCE_FETCH_FAILED = "CONNECTOR_INSTANCE_FETCH_FAILED",
  CONNECTOR_INSTANCE_INVALID_PAYLOAD = "CONNECTOR_INSTANCE_INVALID_PAYLOAD",
  CONNECTOR_INSTANCE_CREATE_FAILED = "CONNECTOR_INSTANCE_CREATE_FAILED",
  CONNECTOR_INSTANCE_USER_NOT_FOUND = "CONNECTOR_INSTANCE_USER_NOT_FOUND",
  CONNECTOR_INSTANCE_DELETE_FAILED = "CONNECTOR_INSTANCE_DELETE_FAILED",
  CONNECTOR_INSTANCE_UPDATE_FAILED = "CONNECTOR_INSTANCE_UPDATE_FAILED",
  CONNECTOR_INSTANCE_WRITE_DISABLED = "CONNECTOR_INSTANCE_WRITE_DISABLED",
  CONNECTOR_INSTANCE_CAPABILITY_NOT_SUPPORTED = "CONNECTOR_INSTANCE_CAPABILITY_NOT_SUPPORTED",

  // Session
  SESSION_PROMPT_INVALID = "SESSION_PROMPT_INVALID",
  SESSION_STREAM_FAILED = "SESSION_STREAM_FAILED",
  SESSION_USER_NOT_FOUND = "SESSION_USER_NOT_FOUND",

  // Jobs
  JOB_NOT_FOUND = "JOB_NOT_FOUND",
  JOB_ALREADY_TERMINAL = "JOB_ALREADY_TERMINAL",
  JOB_ENQUEUE_FAILED = "JOB_ENQUEUE_FAILED",
  JOB_UNAUTHORIZED = "JOB_UNAUTHORIZED",
  JOB_INVALID_PAYLOAD = "JOB_INVALID_PAYLOAD",
  JOB_FETCH_FAILED = "JOB_FETCH_FAILED",
  JOB_CANCEL_FAILED = "JOB_CANCEL_FAILED",
  JOB_SUBSCRIBE_FAILED = "JOB_SUBSCRIBE_FAILED",
  JOB_USER_NOT_FOUND = "JOB_USER_NOT_FOUND",

  // Column Definitions
  COLUMN_DEFINITION_NOT_FOUND = "COLUMN_DEFINITION_NOT_FOUND",
  COLUMN_DEFINITION_FETCH_FAILED = "COLUMN_DEFINITION_FETCH_FAILED",
  COLUMN_DEFINITION_INVALID_PAYLOAD = "COLUMN_DEFINITION_INVALID_PAYLOAD",
  COLUMN_DEFINITION_CREATE_FAILED = "COLUMN_DEFINITION_CREATE_FAILED",
  COLUMN_DEFINITION_UPDATE_FAILED = "COLUMN_DEFINITION_UPDATE_FAILED",
  COLUMN_DEFINITION_DELETE_FAILED = "COLUMN_DEFINITION_DELETE_FAILED",
  COLUMN_DEFINITION_USER_NOT_FOUND = "COLUMN_DEFINITION_USER_NOT_FOUND",
  COLUMN_DEFINITION_HAS_DEPENDENCIES = "COLUMN_DEFINITION_HAS_DEPENDENCIES",
  COLUMN_DEFINITION_TYPE_CHANGE_BLOCKED = "COLUMN_DEFINITION_TYPE_CHANGE_BLOCKED",
  COLUMN_DEFINITION_KEY_IMMUTABLE = "COLUMN_DEFINITION_KEY_IMMUTABLE",

  // Connector Entities
  CONNECTOR_ENTITY_NOT_FOUND = "CONNECTOR_ENTITY_NOT_FOUND",
  CONNECTOR_ENTITY_FETCH_FAILED = "CONNECTOR_ENTITY_FETCH_FAILED",
  CONNECTOR_ENTITY_INVALID_PAYLOAD = "CONNECTOR_ENTITY_INVALID_PAYLOAD",
  CONNECTOR_ENTITY_CREATE_FAILED = "CONNECTOR_ENTITY_CREATE_FAILED",
  CONNECTOR_ENTITY_DELETE_FAILED = "CONNECTOR_ENTITY_DELETE_FAILED",
  CONNECTOR_ENTITY_UPDATE_FAILED = "CONNECTOR_ENTITY_UPDATE_FAILED",
  CONNECTOR_ENTITY_USER_NOT_FOUND = "CONNECTOR_ENTITY_USER_NOT_FOUND",
  ENTITY_HAS_EXTERNAL_REFERENCES = "ENTITY_HAS_EXTERNAL_REFERENCES",

  // Field Mappings
  FIELD_MAPPING_NOT_FOUND = "FIELD_MAPPING_NOT_FOUND",
  FIELD_MAPPING_FETCH_FAILED = "FIELD_MAPPING_FETCH_FAILED",
  FIELD_MAPPING_INVALID_PAYLOAD = "FIELD_MAPPING_INVALID_PAYLOAD",
  FIELD_MAPPING_CREATE_FAILED = "FIELD_MAPPING_CREATE_FAILED",
  FIELD_MAPPING_DUPLICATE_COLUMN = "FIELD_MAPPING_DUPLICATE_COLUMN",
  FIELD_MAPPING_UPDATE_FAILED = "FIELD_MAPPING_UPDATE_FAILED",
  FIELD_MAPPING_DELETE_FAILED = "FIELD_MAPPING_DELETE_FAILED",
  FIELD_MAPPING_USER_NOT_FOUND = "FIELD_MAPPING_USER_NOT_FOUND",
  FIELD_MAPPING_BIDIRECTIONAL_VALIDATION_FAILED = "FIELD_MAPPING_BIDIRECTIONAL_VALIDATION_FAILED",
  FIELD_MAPPING_BIDIRECTIONAL_TARGET_NOT_FOUND = "FIELD_MAPPING_BIDIRECTIONAL_TARGET_NOT_FOUND",

  // Entity Records
  ENTITY_RECORD_NOT_FOUND = "ENTITY_RECORD_NOT_FOUND",
  ENTITY_RECORD_FETCH_FAILED = "ENTITY_RECORD_FETCH_FAILED",
  ENTITY_RECORD_IMPORT_FAILED = "ENTITY_RECORD_IMPORT_FAILED",
  ENTITY_RECORD_INVALID_PAYLOAD = "ENTITY_RECORD_INVALID_PAYLOAD",
  ENTITY_RECORD_INVALID_FILTER = "ENTITY_RECORD_INVALID_FILTER",
  ENTITY_RECORD_DELETE_FAILED = "ENTITY_RECORD_DELETE_FAILED",
  ENTITY_RECORD_UPDATE_FAILED = "ENTITY_RECORD_UPDATE_FAILED",
  ENTITY_RECORD_SYNC_FAILED = "ENTITY_RECORD_SYNC_FAILED",

  // Uploads
  UPLOAD_NO_FILES = "UPLOAD_NO_FILES",
  UPLOAD_INVALID_FILE_TYPE = "UPLOAD_INVALID_FILE_TYPE",
  UPLOAD_FILE_TOO_LARGE = "UPLOAD_FILE_TOO_LARGE",
  UPLOAD_TOO_MANY_FILES = "UPLOAD_TOO_MANY_FILES",
  UPLOAD_S3_ERROR = "UPLOAD_S3_ERROR",
  UPLOAD_INVALID_PAYLOAD = "UPLOAD_INVALID_PAYLOAD",
  UPLOAD_JOB_NOT_PENDING = "UPLOAD_JOB_NOT_PENDING",
  UPLOAD_FILE_MISSING = "UPLOAD_FILE_MISSING",
  UPLOAD_FILE_SIZE_MISMATCH = "UPLOAD_FILE_SIZE_MISMATCH",
  UPLOAD_EMPTY_FILE = "UPLOAD_EMPTY_FILE",
  UPLOAD_PARSE_FAILED = "UPLOAD_PARSE_FAILED",
  UPLOAD_ENCODING_ERROR = "UPLOAD_ENCODING_ERROR",
  UPLOAD_S3_READ_ERROR = "UPLOAD_S3_READ_ERROR",
  UPLOAD_USER_NOT_FOUND = "UPLOAD_USER_NOT_FOUND",
  UPLOAD_AI_ANALYSIS_FAILED = "UPLOAD_AI_ANALYSIS_FAILED",
  UPLOAD_AI_TIMEOUT = "UPLOAD_AI_TIMEOUT",
  UPLOAD_INVALID_STATE = "UPLOAD_INVALID_STATE",
  UPLOAD_INVALID_REFERENCE = "UPLOAD_INVALID_REFERENCE",
  UPLOAD_CONFIRM_TIMEOUT = "UPLOAD_CONFIRM_TIMEOUT",

  // Entity Tags
  ENTITY_TAG_NOT_FOUND = "ENTITY_TAG_NOT_FOUND",
  ENTITY_TAG_FETCH_FAILED = "ENTITY_TAG_FETCH_FAILED",
  ENTITY_TAG_INVALID_PAYLOAD = "ENTITY_TAG_INVALID_PAYLOAD",
  ENTITY_TAG_CREATE_FAILED = "ENTITY_TAG_CREATE_FAILED",
  ENTITY_TAG_UPDATE_FAILED = "ENTITY_TAG_UPDATE_FAILED",
  ENTITY_TAG_DELETE_FAILED = "ENTITY_TAG_DELETE_FAILED",
  ENTITY_TAG_DUPLICATE_NAME = "ENTITY_TAG_DUPLICATE_NAME",
  ENTITY_TAG_USER_NOT_FOUND = "ENTITY_TAG_USER_NOT_FOUND",

  // Entity Tag Assignments
  ENTITY_TAG_ASSIGNMENT_NOT_FOUND = "ENTITY_TAG_ASSIGNMENT_NOT_FOUND",
  ENTITY_TAG_ASSIGNMENT_FETCH_FAILED = "ENTITY_TAG_ASSIGNMENT_FETCH_FAILED",
  ENTITY_TAG_ASSIGNMENT_CREATE_FAILED = "ENTITY_TAG_ASSIGNMENT_CREATE_FAILED",
  ENTITY_TAG_ASSIGNMENT_DELETE_FAILED = "ENTITY_TAG_ASSIGNMENT_DELETE_FAILED",
  ENTITY_TAG_ASSIGNMENT_ALREADY_EXISTS = "ENTITY_TAG_ASSIGNMENT_ALREADY_EXISTS",

  // Entity Groups
  ENTITY_GROUP_NOT_FOUND = "ENTITY_GROUP_NOT_FOUND",
  ENTITY_GROUP_FETCH_FAILED = "ENTITY_GROUP_FETCH_FAILED",
  ENTITY_GROUP_INVALID_PAYLOAD = "ENTITY_GROUP_INVALID_PAYLOAD",
  ENTITY_GROUP_CREATE_FAILED = "ENTITY_GROUP_CREATE_FAILED",
  ENTITY_GROUP_UPDATE_FAILED = "ENTITY_GROUP_UPDATE_FAILED",
  ENTITY_GROUP_DELETE_FAILED = "ENTITY_GROUP_DELETE_FAILED",
  ENTITY_GROUP_DUPLICATE_NAME = "ENTITY_GROUP_DUPLICATE_NAME",
  ENTITY_GROUP_USER_NOT_FOUND = "ENTITY_GROUP_USER_NOT_FOUND",

  // Entity Group Members
  ENTITY_GROUP_MEMBER_NOT_FOUND = "ENTITY_GROUP_MEMBER_NOT_FOUND",
  ENTITY_GROUP_MEMBER_FETCH_FAILED = "ENTITY_GROUP_MEMBER_FETCH_FAILED",
  ENTITY_GROUP_MEMBER_CREATE_FAILED = "ENTITY_GROUP_MEMBER_CREATE_FAILED",
  ENTITY_GROUP_MEMBER_UPDATE_FAILED = "ENTITY_GROUP_MEMBER_UPDATE_FAILED",
  ENTITY_GROUP_MEMBER_DELETE_FAILED = "ENTITY_GROUP_MEMBER_DELETE_FAILED",
  ENTITY_GROUP_MEMBER_ALREADY_EXISTS = "ENTITY_GROUP_MEMBER_ALREADY_EXISTS",
  ENTITY_GROUP_MEMBER_LINK_FIELD_INVALID = "ENTITY_GROUP_MEMBER_LINK_FIELD_INVALID",
  ENTITY_GROUP_MEMBER_PRIMARY_CONFLICT = "ENTITY_GROUP_MEMBER_PRIMARY_CONFLICT",

  // Metadata
  METADATA_MISSING_AUTH = "METADATA_MISSING_AUTH",
  METADATA_USER_NOT_FOUND = "METADATA_USER_NOT_FOUND",
  METADATA_ORGANIZATION_NOT_FOUND = "METADATA_ORGANIZATION_NOT_FOUND",
  METADATA_FETCH_FAILED = "METADATA_FETCH_FAILED",

  // Stations
  STATION_NOT_FOUND = "STATION_NOT_FOUND",

  // Portals
  PORTAL_NOT_FOUND = "PORTAL_NOT_FOUND",
  PORTAL_RESULT_NOT_FOUND = "PORTAL_RESULT_NOT_FOUND",
  PORTAL_INVALID_STATION = "PORTAL_INVALID_STATION",
  PORTAL_STATION_NO_TOOLS = "PORTAL_STATION_NO_TOOLS",
  PORTAL_STREAM_FAILED = "PORTAL_STREAM_FAILED",

  // Organization Tools
  ORG_TOOL_NOT_FOUND = "ORG_TOOL_NOT_FOUND",
  ORG_TOOL_NAME_CONFLICT = "ORG_TOOL_NAME_CONFLICT",

  // Station Tools
  STATION_TOOL_NAME_SHADOW = "STATION_TOOL_NAME_SHADOW",
}
