export enum ApiCode {
  // Profile
  PROFILE_MISSING_TOKEN = "PROFILE_MISSING_TOKEN",
  PROFILE_FETCH_FAILED = "PROFILE_FETCH_FAILED",
  PROFILE_INVALID_RESPONSE = "PROFILE_INVALID_RESPONSE",

  // Auth
  AUTH_UPSTREAM_ERROR = "AUTH_UPSTREAM_ERROR",

  // Health
  HEALTH_CHECK_FAILED = "HEALTH_CHECK_FAILED",
}
