export enum ApplicationRoute {
  Dashboard = "/",
  Settings = "/settings",
  Login = "/login",
  Connectors = "/connectors",
  ConnectorInstance = "/connectors/$connectorInstanceId",
  Entities = "/entities",
  Entity = "/entities/$entityId",
  EntityRecord = "/entities/$entityId/records/$recordId",
  ColumnDefinitions = "/column-definitions",
  ColumnDefinition = "/column-definitions/$columnDefinitionId",
  EntityGroups = "/entity-groups",
  EntityGroup = "/entity-groups/$entityGroupId",
  Jobs = "/jobs",
  Tags = "/tags",
  Portal = "/portals/$portalId",
  Stations = "/stations",
  StationDetail = "/stations/$stationId",
  PortalResults = "/portal-results",
  Help = "/help",
}
